// Component type exports - barrel exports for clean imports

// Upload component types
export type {
  UploadZoneProps,
  UploadProgressProps,
  UploadItem,
  UploadStatus,
  UploadResult,
  ClassificationViewProps,
  FileValidationResult,
  ValidationError,
  FileInfo,
  UploadConfig,
  UploadSettings,
  DragDropState,
  DropEvent,
  UseUploadProps,
  UploadProgress,
  UploadStage,
  UseUploadReturn,
  FilePreviewProps,
  PreviewMetadata,
  BatchUploadProps,
  BatchProgress,
  UploadError,
  ClassificationFeedback,
} from './upload';

// Dashboard component types
export type {
  DashboardProps,
  MetricCardProps,
  TrendData,
  DashboardMetrics,
  DashboardSummary,
  PaymentStatusMetrics,
  StatusBreakdown,
  BillingDestinationMetrics,
  DestinationBreakdown,
  GLAccountMetrics,
  AccountUsage,
  ProcessingMetrics,
  ActivityMetrics,
  RecentClassification,
  SystemEvent,
  UserActivity,
  TrendMetrics,
  TimeSeries,
  PaymentStatusChartProps,
  TrendChartProps,
  DistributionChartProps,
  RecentDocumentsProps,
  RecentDocumentItem,
  DashboardFilters,
  DashboardSettings,
  DashboardMetricType,
  DashboardUpdate,
  MetricUpdate,
  DashboardAlert,
  AlertAction,
} from './dashboard';