// Main types export - barrel exports for clean imports across the app

// Re-export API types with specific exports to avoid conflicts
export type {
  Document,
  DocumentClassification,
  DocumentStatus,
  PaymentStatus,
  PaymentDetectionMethod,
  PaymentDetails,
  PartialPayment,
  BillingDestination,
  ClaudeAnalysis,
  ExtractedEntity,
  ValidationLevel,
  DocumentMetadata,
  AuditStep,
  DocumentUploadRequest,
  DocumentUploadResponse,
  DocumentClassificationRequest,
  DocumentFilters,
  DocumentSortOptions,
  BatchClassificationRequest,
  BatchClassificationResponse,
  DocumentExportRequest,
  DocumentExportResponse,
  GLAccount,
  GLAccountType,
  ClassificationRule,
  RuleCondition,
  MonthlyUsage,
  ExpenseCategory,
  VendorMapping,
  CategoryPattern,
  CategoryUsageStats,
  GLAccountHierarchy,
  GLAccountSetupRequest,
  DefaultAccountMapping,
  QuickBooksSync,
  SyncConflict,
  GLAccountFilters,
  GLAccountSearchResult,
  GLAccountAnalytics,
  AccountUsageSummary,
  AccountTrend,
  MisclassificationSummary,
  ExpenseDistribution,
  SeasonalPattern,
  VendorAccountRelationship,
  BillingRoute,
  RoutingAlgorithm,
  RoutingFactor,
  RuleMatch,
  RoutingHistory,
  ValidationStatus,
  PaymentDetection,
  PaymentMethodResult,
  ConsensusAlgorithm,
  Evidence,
  DocumentLocation,
  PaymentIndicator,
  ConflictingSignal,
  BillingDestinationConfig,
  DestinationRule,
  RuleAction,
  ApprovalWorkflow,
  EscalationRule,
  NotificationSettings as APINotificationSettings,
  NotificationEvent,
  PaymentAnalytics,
  MethodPerformance,
  PaymentStatusDistribution,
  VendorPaymentPattern,
  PaymentSeasonalTrend,
  RouteOptimization,
  RoutePerformanceMetrics,
  SuggestedRule,
  ThresholdAdjustment,
  TrainingRecommendation,
} from './api';

// Re-export all common types
export * from './common';

// Re-export component types with specific exports to avoid conflicts
export type {
  UploadZoneProps,
  UploadProgressProps,
  UploadItem,
  UploadStatus,
  UploadResult,
  ClassificationViewProps,
  FileValidationResult,
  ValidationError,
  FileInfo,
  UploadConfig,
  UploadSettings,
  DragDropState,
  DropEvent,
  UseUploadProps,
  UploadProgress,
  UploadStage,
  UseUploadReturn,
  FilePreviewProps,
  PreviewMetadata,
  BatchUploadProps,
  BatchProgress,
  UploadError,
  ClassificationFeedback,
  DashboardProps,
  MetricCardProps,
  TrendData,
  DashboardMetrics,
  DashboardSummary,
  PaymentStatusMetrics,
  StatusBreakdown,
  BillingDestinationMetrics,
  DestinationBreakdown,
  GLAccountMetrics,
  AccountUsage,
  ProcessingMetrics,
  ActivityMetrics,
  RecentClassification,
  SystemEvent,
  UserActivity,
  TrendMetrics,
  TimeSeries,
  PaymentStatusChartProps,
  TrendChartProps,
  DistributionChartProps,
  RecentDocumentsProps,
  RecentDocumentItem,
  DashboardFilters,
  DashboardSettings as ComponentDashboardSettings,
  DashboardMetricType,
  DashboardUpdate,
  MetricUpdate,
  DashboardAlert,
  AlertAction,
} from './components';

// Re-export auth types with aliases to avoid conflicts
export type {
  User,
  UserRole,
  Permission,
  PermissionResource,
  PermissionAction,
  PermissionCondition,
  UserSettings,
  NotificationSettings as AuthNotificationSettings,
  DashboardSettings as AuthDashboardSettings,
  UISettings,
  AuthState,
  AuthTokens,
  LoginCredentials,
  LoginResponse,
  RefreshTokenResponse,
  RegisterRequest,
  RegisterResponse,
  EmailVerificationRequest,
  PasswordResetRequest,
  PasswordResetResponse,
  PasswordUpdateRequest,
  TenantAuthConfig,
  PasswordPolicy,
  SSOConfig,
  SSOLoginRequest,
  SessionInfo,
  SessionActivity,
  SecurityEvent,
  AuditLog,
  ApiKey,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
} from './auth';

// Type guards and utilities
export const isDocument = (obj: any): obj is import('./api').Document => {
  return obj && typeof obj.id === 'string' && typeof obj.filename === 'string';
};

export const isValidPaymentStatus = (status: string): status is import('./api').PaymentStatus => {
  return ['paid', 'unpaid', 'partial', 'void', 'unknown'].includes(status);
};

export const isBillingDestination = (dest: string): dest is import('./api').BillingDestination => {
  return ['open_payable', 'closed_payable', 'open_receivable', 'closed_receivable'].includes(dest);
};

export const isGLAccountType = (type: string): type is import('./api').GLAccountType => {
  return [
    'asset',
    'liability',
    'equity',
    'income',
    'expense',
    'cost_of_goods_sold',
    'other_income',
    'other_expense',
  ].includes(type);
};