// Auth type exports - barrel exports for clean imports

export type {
  User,
  UserRole,
  Permission,
  PermissionResource,
  PermissionAction,
  PermissionCondition,
  UserSettings,
  NotificationSettings,
  DashboardSettings,
  UISettings,
  AuthState,
  AuthTokens,
  LoginCredentials,
  LoginResponse,
  RefreshTokenResponse,
  RegisterRequest,
  RegisterResponse,
  EmailVerificationRequest,
  PasswordResetRequest,
  PasswordResetResponse,
  PasswordUpdateRequest,
  TenantAuthConfig,
  PasswordPolicy,
  SSOConfig,
  SSOLoginRequest,
  SessionInfo,
  SessionActivity,
  SecurityEvent,
  AuditLog,
  ApiKey,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
} from './auth';